/**
 * Image Generator Widget
 *
 * Full React UI for generating images with AI using Replicate models.
 * Generates entities straight onto the canvas.
 * Clicking an entity allows it to be edited in the widget.
 *
 * @module runtime/widgets/image-generator
 */

import React, { useState, useCallback, useMemo } from 'react';

import type { WidgetManifest } from '@sn/types';
import { CanvasEvents } from '@sn/types';

import { useEmit, useSubscribe, useWidgetState } from '../../hooks';
import { getIntegrationProxy } from '../../integrations/singleton';

const REPLICATE_MODELS = [
  { label: 'Flux Schnell (Fast)', id: 'black-forest-labs/flux-schnell' },
  { label: 'Flux Dev (Quality)', id: 'black-forest-labs/flux-dev' },
  { label: 'Stable Diffusion XL', id: 'stability-ai/sdxl' },
  { label: 'SDXL Lightning', id: 'bytedance/sdxl-lightning-4step' },
];

/**
 * Image Generator Widget manifest.
 */
export const imageGeneratorManifest: WidgetManifest = {
  id: 'sn.builtin.image-generator',
  name: 'AI Image Generator',
  version: '1.0.0',
  description: 'Generate AI images and place them on the canvas',
  author: { name: 'StickerNest', url: 'https://stickernest.com' },
  category: 'media',
  tags: ['ai', 'image', 'replicate'],
  permissions: ['ai'],
  size: { defaultWidth: 320, defaultHeight: 480, minWidth: 280, minHeight: 400, aspectLocked: false },
  license: 'MIT',
  config: { fields: [] },
  spatialSupport: false,
  entry: 'inline',
  events: {
    emits: [
      { name: 'widget.image-generator.ready' },
      { name: 'widget.image-generator.generation.started' },
      { name: 'widget.image-generator.generation.completed' },
      { name: 'widget.image-generator.generation.failed' },
    ],
    subscribes: [
      { name: 'canvas.entity.selected' },
      { name: 'canvas.selection.cleared' },
    ],
  },
};

/**
 * Image Generator Widget component.
 */
export const ImageGeneratorWidget: React.FC<any> = ({ instanceId }) => {
  const emit = useEmit();
  const [state, setState] = useWidgetState(instanceId);

  const [prompt, setPrompt] = useState(state.lastPrompt || '');
  const [model, setModel] = useState(state.lastModel || REPLICATE_MODELS[0].id);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastImageUrl, setLastImageUrl] = useState<string | null>(null);
  const [selectedEntityId, setSelectedEntityId] = useState<string | null>(null);

  // AI Integration via Singleton Proxy (as handled by host runtime)
  const ai = useMemo(() => getIntegrationProxy().integration('ai'), []);

  // Handle generation
  const handleGenerate = useCallback(async () => {
    if (!prompt) return;

    setIsGenerating(true);
    setError(null);

    try {
      const result = await ai.query({
        action: 'generate-image',
        model,
        input: {
          prompt,
          aspect_ratio: '1:1',
        }
      }) as { output: string[] | string };

      if (result && result.output) {
        const imageUrl = Array.isArray(result.output) ? result.output[0] : result.output;
        setLastImageUrl(imageUrl);

        // Save last state
        setState('lastPrompt', prompt);
        setState('lastModel', model);

        // Generate entity on canvas
        const entityId = crypto.randomUUID();
        emit(CanvasEvents.ENTITY_CREATED, {
          id: entityId,
          type: 'sticker',
          assetUrl: imageUrl,
          assetType: 'image' as const,
          name: `AI: ${prompt.slice(0, 20)}...`,
          altText: prompt,
          transform: {
            position: { x: 400, y: 300 }, // Center-ish
            size: { width: 400, height: 400 },
            rotation: 0,
            scale: 1,
          },
          config: {
            aiPrompt: prompt,
            aiModel: model,
            generatedBy: instanceId,
          }
        });
      } else {
        setError('Generation failed: No output received');
      }
    } catch (err: any) {
      setError(err.message || 'Error calling AI service');
    } finally {
      setIsGenerating(false);
    }
  }, [ai, prompt, model, emit, instanceId, setState]);

  // Subscribe to selection events to allow editing
  useSubscribe('widget.canvas.entity.selected', (payload: any) => {
    const entities = payload.entities || [];
    if (entities.length === 1) {
      const entity = entities[0];
      // Check if this entity was generated by this widget instance
      if (entity.config?.generatedBy === instanceId) {
        setSelectedEntityId(entity.id);
        setPrompt(entity.config.aiPrompt || '');
        setModel(entity.config.aiModel || REPLICATE_MODELS[0].id);
        setLastImageUrl(entity.assetUrl);
      }
    } else {
      setSelectedEntityId(null);
    }
  });

  // Handle selection cleared
  useSubscribe('widget.canvas.selection.cleared', () => {
    setSelectedEntityId(null);
  });

  // Handle updates to existing entity
  const handleUpdate = useCallback(() => {
    if (!selectedEntityId) return;

    emit(CanvasEvents.ENTITY_UPDATED, {
      id: selectedEntityId,
      updates: {
        altText: prompt,
        name: `AI: ${prompt.slice(0, 20)}...`,
        config: {
          aiPrompt: prompt,
          aiModel: model,
          generatedBy: instanceId,
        }
      }
    });
  }, [selectedEntityId, prompt, model, emit, instanceId]);

  return (
    <div style={{
      padding: '16px',
      height: '100%',
      background: 'var(--sn-surface, #fff)',
      color: 'var(--sn-text, #333)',
      fontFamily: 'var(--sn-font-family, sans-serif)',
      display: 'flex',
      flexDirection: 'column',
      gap: '12px',
      overflowY: 'auto',
      boxSizing: 'border-box',
    }}>
      <div style={{ fontWeight: 600, fontSize: '14px', marginBottom: '4px' }}>
        {selectedEntityId ? 'Edit Selected AI Image' : 'Generate AI Image'}
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
        <label style={{ fontSize: '12px', color: 'var(--sn-text-muted, #666)' }}>Prompt</label>
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe what you want to see..."
          style={{
            minHeight: '80px',
            padding: '8px',
            borderRadius: '6px',
            border: '1px solid var(--sn-border, #e5e5e5)',
            background: 'var(--sn-bg, #f9f9f9)',
            color: 'inherit',
            fontSize: '13px',
            resize: 'vertical',
            outline: 'none',
          }}
        />
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
        <label style={{ fontSize: '12px', color: 'var(--sn-text-muted, #666)' }}>Model</label>
        <select
          value={model}
          onChange={(e) => setModel(e.target.value)}
          style={{
            padding: '8px',
            borderRadius: '6px',
            border: '1px solid var(--sn-border, #e5e5e5)',
            background: 'var(--sn-bg, #f9f9f9)',
            color: 'inherit',
            fontSize: '13px',
            outline: 'none',
          }}
        >
          {REPLICATE_MODELS.map((m) => (
            <option key={m.id} value={m.id}>{m.label}</option>
          ))}
        </select>
      </div>

      <button
        onClick={selectedEntityId ? handleUpdate : handleGenerate}
        disabled={isGenerating || !prompt}
        style={{
          padding: '10px',
          borderRadius: '8px',
          background: 'var(--sn-accent, #3b82f6)',
          color: '#fff',
          border: 'none',
          fontWeight: 600,
          cursor: (isGenerating || !prompt) ? 'not-allowed' : 'pointer',
          opacity: (isGenerating || !prompt) ? 0.7 : 1,
          marginTop: '8px',
        }}
      >
        {isGenerating ? 'Generating...' : selectedEntityId ? 'Update Entity' : 'Generate'}
      </button>

      {error && (
        <div style={{
          padding: '8px',
          background: '#fee2e2',
          color: '#991b1b',
          borderRadius: '6px',
          fontSize: '12px',
        }}>
          {error}
        </div>
      )}

      {lastImageUrl && (
        <div style={{ marginTop: '12px' }}>
          <div style={{ fontSize: '12px', color: 'var(--sn-text-muted, #666)', marginBottom: '4px' }}>
            Latest Generation:
          </div>
          <img
            src={lastImageUrl}
            alt="Generated"
            style={{
              width: '100%',
              borderRadius: '8px',
              border: '1px solid var(--sn-border, #e5e5e5)',
              background: '#000',
            }}
          />
        </div>
      )}

      {selectedEntityId && (
        <button
          onClick={() => setSelectedEntityId(null)}
          style={{
            padding: '6px',
            background: 'none',
            border: 'none',
            color: 'var(--sn-accent, #3b82f6)',
            fontSize: '12px',
            cursor: 'pointer',
            textAlign: 'center',
          }}
        >
          Back to New Generation
        </button>
      )}

      <div style={{ flex: 1 }} />

      <div style={{ fontSize: '10px', color: 'var(--sn-text-muted, #999)', textAlign: 'center' }}>
        Instance: {instanceId.slice(0, 8)} | Replicate Integration
      </div>
    </div>
  );
};
